### ISSUE TITLE
Can't go to URL anymore

### ISSUE THREAD

**Issue by onli** [Quicksaver/Omnibar-Plus#13]
Since today, when entering a URL into the Omnibar while having Omnibar-Plus active, I can't got to the site anymore. Pressing enter does nothing, the same goes for clicking on the arrow at the right.

FF 43.0 under Linux (Ubuntu).

**Comment by Quicksaver** [comment]
Does the same happen if you disable all your other add-ons except for Omnibar and Omnibar Plus?

**Comment by onli** [comment]
No. I deacitvated all other addons and it worked. I then re-activated the other addons one by one to find the conflict, but having all activated it still works. Very strange.

Thanks though, at least for now that fixed it.
