### ISSUE TITLE
search exact text by default

### ISSUE THREAD

**Issue by brettatoms** [Quicksaver/Omnibar-Plus#2]
I would like to request an option to add "search for  typed text by default" to Ombibar-Plus.  One of the best things about Chrome is that if you enter some text in the location bar and that text doesn't match a URL then the first item in the popup list is link to a google search for the text.  The location bar still matches titles and bookmarks but usually if I'm typing in some random text it's because I want to search for the string rather than match a title.

For example, if I enter "local food" I don't want a page with a title that matches "local food" I want to search for it.  I don't even know if most people even pay attention to the titles of web pages.  At the moment with Omnibar/Plus is suggested searches are grouped at the bottom and the exact string you typed in is the last item meaning it's several key presses to search for the exact text or my hands have to leave the keyboard and grab the mouse.  having them grouped at the bottom doesn't really matter but I think it would be best to just type some text, hit enter, and a list of search results show up.

**Comment by Quicksaver** [comment]
If no entry is selected in the dropdown then it should search for the string when hitting enter, regardless of what entries there are in the list. Is this not happening?

The only exception to this is if you have the Speak Words add-on enabled, which auto-selects the first result by default.

Also if it's the last entry you want (again, if it's the exact same as what you typed you don't need to select anything, just press enter) you can always press the up key and it will surf the list backwards.

**Comment by brettatoms** [comment]
I didn't realize it was Speak Words that was causing the auto-select
even though I had the "Always select the first result even for
domains".  Thanks.

Without Speak Words I don't get domain completion, which sucks, but I
guess that's not your problem.  This bug can be closed.

On Fri, Nov 11, 2011 at 9:14 AM, Quicksaver
reply@reply.github.com
wrote:

**Comment by Quicksaver** [comment]
I'm reopening this because it gave me an idea, I might add an option that autoselects the first result, which you can enable/disable in the options dialog. This way it will both override speak words in that aspect, giving you more control over what behavior you want, and give you that ability without needing speak words enabled if that's all you want.

**Comment by Quicksaver** [comment]
Will be in the next release.
