### ISSUE TITLE
Omnibar feels really slow on linux with Omnibar Plus active

### ISSUE THREAD

**Issue by leoriccio** [Quicksaver/Omnibar-Plus#3]
Like the title says, it seems to me that Omnibar Plus really slows the Omnibar, but only linux, on windows it works really well.

If you need any information ask away.

**Comment by Quicksaver** [comment]
I've never noticed this, but I haven't checked Omnibar Plus in linux for a while now, I may have broken something in the later versions. I will try it to see if there's something I can do for the next release.

**Comment by Quicksaver** [comment]
Could you please try the latest beta version of the add-on to see if it improved this issue in linux? You can find it at the bottom of the page at https://addons.mozilla.org/en-US/firefox/addon/omnibar-plus/ in the development channel.

Direct link: https://addons.mozilla.org/firefox/downloads/file/147178/omnibar_plus-0.7b1-fx.xpi?src=dp-btn-devchannel

**Comment by Quicksaver** [comment]
I forgot to explain what I did. I think it's the animated popup style that's causing some trouble in linux, I tried tweaking it a bit to hopefully improve this.

**Comment by leoriccio** [comment]
Unfortunatly yesterday I had to format my HD and reinstall everything, so I can't try the addons on the same environment, but on a clean SO, the new versione seems fine. 
I think that in a few days I will have a more complete opinion (and a less clean SO :P).

Thanks for your work!

**Comment by leoriccio** [comment]
After 6 days I still don't see any performance problem. But the autoselect first result is always active, even when the pref is unchecked.

**Comment by Quicksaver** [comment]
Yes the autoselect thing is a bug I have to fix before I release the new version.
