### ISSUE TITLE
Auto-select first entry broken under certain circumstances

### ISSUE THREAD

**Issue by matrus** [Quicksaver/Omnibar-Plus#5]
STR:
1. Create a new profile
2. Install Ominibar and Omnibar Plus
3. Deactivate "Organize suggestion list"
4. Turn on "Auto-select the first suggestion in the list"
5. Enter a string into the location bar until it matches a bookmark or history item.
6. Hit Enter

Actual result:
The typed string is send to whatever search engine is currently selected despite the first entry being selected.

Expected result:
The first entry is selected.

**Comment by Quicksaver** [comment]
Yes, it's been broken in the last few releases of firefox. I haven't had time to fix it yet but I will.
