### ISSUE TITLE
Omnibar Plus Breaks Omnibar's Search Engine Selection List

### ISSUE THREAD

**Issue by mcl21014** [Quicksaver/Omnibar-Plus#6]
Well, I was using Firefox as usual (v20 beta on Raring development branch) and today noticed that when I go to change my search engine via omnibar, it will not come up with the list to select a search engine. I don't know how to explain it, but this bug went away when I removed Omnibar Plus and restarted Firefox. Any errors I can upload? I am going to check and see if this happens on Nightly Firefox, and on Windows as well. I have isolated the issue to relating to these two addons. I restarted in safe mode with Firefox to see what addon was causing this, and after enough testing, I found it to be omnibar plus. If there's any specific logs you need, let me know where I can find them and which ones you want. I went to about:config and tried resetting omnibar and omnibar plus's about:config values, and the same issue repeated.

**Comment by Quicksaver** [comment]
Omnibar Plus has been having some problems in the latest versions of firefox, which I've been unable to fix due to lack of time. I have never experienced this behavior, but once I get back to coding the add-on, I will be sure to check your issue and try to fix it.

**Comment by Quicksaver** [comment]
This should be fixed in the next version (1.0.5).
