### ISSUE TITLE
Color schemes in Firefox > 20

### ISSUE THREAD

**Issue by WeAreGeek** [Quicksaver/Omnibar-Plus#7]
It seems the color schemes aren't working anymore, since the upgrade to Firefox 20.
If you need any specific information, please let me know.

**Comment by Quicksaver** [comment]
Please try the latest version 1.0.5. It should work with that version. It's not yet been reviewed by the AMO reviewers team, but you can find it at https://addons.mozilla.org/en-US/firefox/addon/omnibar-plus/versions/ . Let me know if it works with that version.

**Comment by WeAreGeek** [comment]
Hi! Thanks for the quick reply; that was really fast! ;-)
I installed 1.0.5 and I can confirm it works. Thank you very much!

**Comment by Quicksaver** [comment]
Glad to hear it. :)
