### ISSUE TITLE
Addon conlifcts

### ISSUE THREAD

**Issue by 0Raik** [Quicksaver/Omnibar-Plus#9]
When used together with Stay-open Menu extension the drop down suggestion links become unclickable, already reported to the developer of Stay-open Menu here 

http://forums.mozillazine.org/viewtopic.php?f=48&t=633732&start=150 

He made a temp fix but disables the option to keep open the dropdown menu, would be nice to have them fixed and working together, also the developer requested you to be informed of this:

"I also noticed that Omnibar Plus seems to entirely disable ctrl-click and middle-click on those drop-down suggestions (even without Stay-Open Menu installed). You might want to report that to its author as a bug."

**Comment by Quicksaver** [comment]
First of all, I'm sorry it took me so long to reply.

Thanks for reporting this to me, I've fixed it already and the next version (probably 1.0.11) should work properly with the Stay-Open Menu add-on. You can find it at https://addons.mozilla.org/en-US/firefox/addon/omnibar-plus/versions/ if you'd like to try it, it's at the top with version 1.0.11b. (make sure you re-install the proper versino of stay-open menu and not the temporary fix its developer made for this of course).

Also, with that beta version, could you tell me please if ctrl+click and middle click work properly? They seem to work perfectly for me so I don't understand that comment for SOM's developer, I'll ask him the same in that thread you posted to be sure.

**Comment by 0Raik** [comment]
Thank you so much for the hard work and have a nice day :D
